"""
Tests for hokusai.nodes.phase4_plan module

Phase 4 出力検証の強化テスト:
- _extract_dev_plan_content() のマーカー拡充
- _validate_work_plan() の妥当性検証
- 抽出失敗判定の正確性（プレフィックスマッチ含む）
- 妥当性ゲート
- phase4_plan_node() 統合テスト
"""

import pytest
from unittest.mock import patch, MagicMock

from hokusai.nodes.phase4_plan import (
    _extract_dev_plan_content,
    _validate_work_plan,
    _DEV_PLAN_START_MARKERS,
    extract_expected_files_from_dev_plan,
)
from hokusai.state import PhaseStatus
from hokusai.utils.output_parser import _find_prefix_heading


class TestExtractDevPlanContent:
    """_extract_dev_plan_content のテスト"""

    def test_with_heading(self):
        """見出しありで正しく抽出"""
        output = """はい、開発計画を作成します。

## 開発計画

- [ ] **1.1** APIスキーマ変更
- [ ] **1.2** バックエンド実装

### 変更予定ファイル
- src/api.ts
"""
        result = _extract_dev_plan_content(output)

        assert "## 開発計画" in result
        assert "1.1" in result
        assert "はい、開発計画を作成します" not in result

    def test_no_heading(self):
        """見出しなしで raw output を返す"""
        output = "LLMからの応答テキストでマーカーなし"
        result = _extract_dev_plan_content(output)

        assert result == output

    def test_expanded_markers_checklist(self):
        """「実装チェックリスト」マーカーでマッチ"""
        output = """前置きテキスト

## 実装チェックリスト

- [ ] **1.1** 機能A
- [ ] **2.0** 機能B
"""
        result = _extract_dev_plan_content(output)

        assert "## 実装チェックリスト" in result
        assert "前置きテキスト" not in result

    def test_expanded_markers_plan_points(self):
        """「計画のポイント」マーカーでマッチ"""
        output = """概要です。

### 計画のポイント

1.1 最初のステップ
2.0 次のステップ
"""
        result = _extract_dev_plan_content(output)

        assert "### 計画のポイント" in result
        assert "概要です。" not in result

    def test_end_marker_generated_by(self):
        """Generated by で切断される"""
        output = """## 開発計画

- [ ] **1.1** 機能A

Generated by Claude
"""
        result = _extract_dev_plan_content(output)

        assert "1.1" in result
        assert "Generated by" in result


class TestValidateWorkPlan:
    """_validate_work_plan のテスト"""

    def test_valid_checklist(self):
        """有効なチェックリスト"""
        text = """## 開発計画
- [ ] **1.1** APIスキーマ変更
- [ ] **1.2** バックエンド実装
- [ ] **2.0** フロントエンド実装
- [ ] **3.0** テスト追加
"""
        is_valid, warnings = _validate_work_plan(text)
        assert is_valid is True
        assert warnings == []

    def test_no_steps(self):
        """ステップ不足で warning"""
        text = "ただのテキストです。ステップがありません。"
        is_valid, warnings = _validate_work_plan(text)
        assert is_valid is False
        assert any("ステップ番号が少なすぎます" in w for w in warnings)

    def test_no_checkboxes_no_numbered(self):
        """チェックボックスもステップ番号もなしで warning"""
        text = "単なるテキスト"
        is_valid, warnings = _validate_work_plan(text)
        assert is_valid is False
        assert any("チェックリスト形式" in w for w in warnings)

    def test_numbered_without_checkboxes(self):
        """番号付きだがチェックボックスなし — ステップ数十分なら有効"""
        text = """1.1 最初のステップ
1.2 次のステップ
2.0 三番目のステップ
"""
        is_valid, warnings = _validate_work_plan(text)
        assert is_valid is True
        assert warnings == []

    def test_few_steps_warning(self):
        """ステップ数が少ない場合は warning"""
        text = """- [ ] **1.1** 唯一のステップ
"""
        is_valid, warnings = _validate_work_plan(text)
        assert is_valid is False
        assert any("少なすぎます" in w for w in warnings)


class TestExtractExpectedFiles:
    """extract_expected_files_from_dev_plan のテスト"""

    def test_extract_files(self):
        """変更予定ファイルを抽出"""
        result = """## 開発計画

### 変更予定ファイル
- src/api.ts
- src/components/Feature.tsx
"""
        files = extract_expected_files_from_dev_plan(result)
        assert "src/api.ts" in files
        assert "src/components/Feature.tsx" in files

    def test_empty_when_no_section(self):
        """セクションなしで空リスト"""
        result = "## 開発計画\n内容のみ"
        files = extract_expected_files_from_dev_plan(result)
        assert files == []


class TestExtractionSucceededDetection:
    """抽出成否判定の正確性テスト（Phase 4 の extraction_succeeded ロジック）

    Phase 4 では以下で判定:
        extraction_succeeded = (
            (output_text != raw_output)
            or _find_prefix_heading(raw_output, _DEV_PLAN_START_MARKERS) is not None
        )
    """

    def _is_extraction_succeeded(self, raw_output: str) -> bool:
        """Phase 4 と同じ判定ロジックを再現"""
        output_text = _extract_dev_plan_content(raw_output)
        return (
            (output_text != raw_output)
            or _find_prefix_heading(raw_output, _DEV_PLAN_START_MARKERS) is not None
        )

    def test_output_starting_with_marker_is_success(self):
        """出力が ## 開発計画 から始まる場合は抽出成功（誤判定しない）"""
        output = "## 開発計画\n- [ ] **1.1** 機能A\n- [ ] **1.2** 機能B\n"
        assert self._is_extraction_succeeded(output) is True

    def test_no_marker_is_genuine_failure(self):
        """マーカーなしの出力は抽出失敗として検知"""
        output = "はい、タスクを確認しました。他に何かありますか？"
        assert self._is_extraction_succeeded(output) is False

    def test_marker_in_middle_is_success(self):
        """マーカーが途中にある場合は抽出成功（前置きが除去される）"""
        output = "前置きテキスト\n\n## 開発計画\n- [ ] **1.1** 機能A\n"
        assert self._is_extraction_succeeded(output) is True
        # 前置きが除去されていることも確認
        result = _extract_dev_plan_content(output)
        assert "前置きテキスト" not in result

    def test_prefix_match_heading_is_success(self):
        """プレフィックスマッチ（例: ### 開発計画のまとめ）でも抽出成功"""
        output = "前置き\n\n### 開発計画のまとめ\n1.1 ステップA\n2.0 ステップB\n"
        # _find_prefix_heading は "### 計画のポイント" とのプレフィックスマッチで
        # "### 開発計画のまとめ" を検出しないが、"## 開発計画" → "開発計画" が
        # "開発計画のまとめ" の先頭とマッチする
        assert self._is_extraction_succeeded(output) is True

    def test_completely_unrelated_heading_is_failure(self):
        """無関係な見出しのみの出力は抽出失敗"""
        output = "## タスク完了報告\n作業を完了しました。1.1 と 2.0 の修正済み。"
        assert self._is_extraction_succeeded(output) is False


class TestPhase4ValidationGate:
    """Phase 4 妥当性ゲートのテスト（_validate_work_plan が Phase 4 完了を阻止）"""

    def test_invalid_plan_blocks_completion(self):
        """不正な計画は is_valid=False で返り、ゲートに使える"""
        invalid_text = "LLM プリアンブルのみ。チェックリストなし。"
        is_valid, warnings = _validate_work_plan(invalid_text)
        assert is_valid is False
        assert len(warnings) > 0

    def test_valid_plan_passes_gate(self):
        """有効な計画は is_valid=True でゲートを通過"""
        valid_text = (
            "## 開発計画\n"
            "- [ ] **1.1** APIスキーマ変更\n"
            "- [ ] **1.2** バックエンド実装\n"
            "- [ ] **2.0** フロントエンド実装\n"
        )
        is_valid, warnings = _validate_work_plan(valid_text)
        assert is_valid is True
        assert warnings == []


class TestPhase4PlanNodeIntegration:
    """phase4_plan_node() の統合テスト — ゲートが実際に Phase 4 を止めるか検証"""

    VALID_PLAN = (
        "## 開発計画\n"
        "- [ ] **1.1** APIスキーマ変更\n"
        "- [ ] **1.2** バックエンド実装\n"
        "- [ ] **2.0** フロントエンド実装\n"
        "### 変更予定ファイル\n"
        "- src/api.ts\n"
    )

    @patch("hokusai.nodes.phase4_plan.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.save_to_subpage_or_create", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.ClaudeCodeClient")
    def test_extraction_failure_blocks_phase4(
        self, mock_claude_cls, mock_save, mock_cross_review, minimal_state,
    ):
        """見出し抽出失敗時に Phase 4 が FAILED になり raw output が work_plan に入らない"""
        from hokusai.nodes.phase4_plan import phase4_plan_node

        mock_claude = MagicMock()
        # マーカーを含まない出力 → 抽出失敗
        mock_claude.execute_skill.return_value = {
            "work_plan": "はい、タスクを確認しました。他に何かお手伝いできますか？"
        }
        # リトライ（execute_prompt）でも同様に失敗する出力
        mock_claude.execute_prompt.return_value = "リトライしましたが同じ結果です。"
        mock_claude_cls.return_value = mock_claude

        result = phase4_plan_node(minimal_state)

        assert result["phases"][4]["status"] == PhaseStatus.FAILED.value
        # raw output が work_plan に保存されていない
        assert result.get("work_plan") is None
        # リトライが実行された
        mock_claude.execute_prompt.assert_called_once()
        # Notion 保存やクロスレビューは実行されない
        mock_save.assert_not_called()
        mock_cross_review.assert_not_called()

    @patch("hokusai.nodes.phase4_plan.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.save_to_subpage_or_create", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.ClaudeCodeClient")
    def test_validation_failure_blocks_phase4(
        self, mock_claude_cls, mock_save, mock_cross_review, minimal_state,
    ):
        """妥当性検証失敗時に Phase 4 が FAILED になる（Notion 保存後にゲート）"""
        from hokusai.nodes.phase4_plan import phase4_plan_node

        mock_claude = MagicMock()
        # マーカーありだがステップ不足 → 抽出成功、検証失敗
        mock_claude.execute_skill.return_value = {
            "work_plan": "## 開発計画\nステップなしの概要のみ"
        }
        mock_claude_cls.return_value = mock_claude

        result = phase4_plan_node(minimal_state)

        assert result["phases"][4]["status"] == PhaseStatus.FAILED.value
        # Notion には保存される（デバッグ用）
        mock_save.assert_called_once()
        # クロスレビューは実行されない（ゲートで停止）
        mock_cross_review.assert_not_called()

    @patch("hokusai.nodes.phase4_plan.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.save_to_subpage_or_create", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase4_plan.ClaudeCodeClient")
    def test_valid_plan_completes_phase4(
        self, mock_claude_cls, mock_save, mock_cross_review, minimal_state,
    ):
        """有効な計画で Phase 4 が COMPLETED になる"""
        from hokusai.nodes.phase4_plan import phase4_plan_node

        mock_claude = MagicMock()
        mock_claude.execute_skill.return_value = {"work_plan": self.VALID_PLAN}
        mock_claude_cls.return_value = mock_claude

        result = phase4_plan_node(minimal_state)

        assert result["phases"][4]["status"] == PhaseStatus.COMPLETED.value
        assert result["work_plan"] is not None
        assert "1.1" in result["work_plan"]
        mock_save.assert_called_once()
        saved_content = mock_save.call_args.kwargs.get("content") or mock_save.call_args[0][3]
        assert "# Phase 4: 作業計画" in saved_content
        assert "## 進捗チェックリスト" in saved_content
        assert "## 最新版ドキュメント" in saved_content
        assert self.VALID_PLAN in saved_content
        mock_cross_review.assert_called_once()
