"""
Phase 2 事前調査ノード / 抽出ロジックのテスト

テスト対象:
- _extract_research_report: マーカー揺れ対応・会話文混入ガード
- phase2_research_node: Notion二重保存が発生しないこと
- NotionMCPClient.insert_after_existing: after_marker がプロンプトに反映されること
- fail-fast: 子ページ作成失敗時に Phase 2 が失敗すること
- _verify_notion_state: 事後検証
"""

from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from hokusai.nodes.phase2_research import _extract_research_report


# ---------------------------------------------------------------------------
# _extract_research_report テスト
# ---------------------------------------------------------------------------

class TestExtractResearchReport:
    """調査レポート抽出のテスト"""

    def test_standard_marker(self):
        """標準マーカー「## 事前調査結果」で抽出できる"""
        output = (
            "調査を開始します。\n\n"
            "## 事前調査結果\n\n"
            "### タスク概要\nテスト用タスク\n\n"
            "Generated by `/task-research`\n\n"
            "他に作業はありますか？"
        )
        result = _extract_research_report(output)
        assert "### タスク概要" in result
        assert "他に作業はありますか" not in result

    def test_alternative_marker_report(self):
        """代替マーカー「## 事前調査レポート」で抽出できる"""
        output = (
            "了解しました。\n\n"
            "## 事前調査レポート\n\n"
            "### タスク概要\n内容\n\n"
            "Generated by `/task-research`"
        )
        result = _extract_research_report(output)
        assert "## 事前調査レポート" in result
        assert "了解しました" not in result

    def test_summary_marker_no_longer_extracted(self):
        """「## 調査結果サマリー」はフルレポート系マーカーから除外されている"""
        output = (
            "調査完了です。\n\n"
            "## 調査結果サマリー\n\n"
            "### 概要\nサマリー内容\n\n"
            "Generated by `/task-research`"
        )
        result = _extract_research_report(output)
        assert result == ""

    def test_no_marker_returns_empty(self):
        """マーカーが見つからない場合は空文字列を返す（会話文丸ごと保存を防止）"""
        output = "何かお手伝いできることはありますか？調査結果は以下です。"
        result = _extract_research_report(output)
        assert result == ""

    def test_empty_input(self):
        """空入力は空文字列を返す"""
        result = _extract_research_report("")
        assert result == ""

    def test_summary_prefix_no_longer_extracted(self):
        """「## 調査結果サマリ」(長音なし)もサマリー系マーカー除外により抽出されない"""
        output = (
            "事前調査が完了し、Notionタスクページに追記しました。\n\n"
            "## 調査結果サマリ\n\n"
            "### タスク概要\n表示機能追加\n\n"
            "Generated by `/task-research`"
        )
        result = _extract_research_report(output)
        assert result == ""

    def test_prefix_match_with_extra_suffix(self):
        """「## 事前調査レポート（概要）」のように末尾が拡張されても抽出できる"""
        output = (
            "了解です。\n\n"
            "## 事前調査レポート（概要）\n\n"
            "### 1. 現状\n内容\n\n"
            "Generated by /task-research"
        )
        result = _extract_research_report(output)
        assert "### 1. 現状" in result
        assert "了解です" not in result

    def test_h3_summary_marker_no_longer_extracted(self):
        """「### 調査結果のサマリー」はフルレポート系マーカーから除外されている"""
        output = (
            "事前調査が完了しました。調査レポートをNotionタスクページに追記しました。\n\n"
            "### 調査結果のサマリー\n\n"
            "**タスク**: ユーザー管理で質問一覧表示\n\n"
            "Generated by `/task-research`"
        )
        result = _extract_research_report(output)
        assert result == ""

    def test_h3_exact_match(self):
        """### 事前調査結果 の完全一致で抽出できる"""
        output = (
            "了解しました。\n\n"
            "### 事前調査結果\n\n"
            "### タスク概要\n内容\n\n"
            "Generated by `/task-research`"
        )
        result = _extract_research_report(output)
        assert "### タスク概要" in result
        assert "了解しました" not in result

    def test_output_starts_with_heading_h2(self):
        """出力が ## 見出しから始まる場合（前置きなし）でも空にならない"""
        output = "## 事前調査結果\n\n本文のみ"
        result = _extract_research_report(output)
        assert "本文のみ" in result
        assert result != ""

    def test_output_starts_with_summary_h3_returns_empty(self):
        """「### 調査結果のサマリー」で始まる出力は抽出されない（サマリーマーカー除外済み）"""
        output = "### 調査結果のサマリー\n\n**タスク**: テスト\n\n詳細内容"
        result = _extract_research_report(output)
        assert result == ""

    def test_no_heading_still_returns_empty(self):
        """見出しがない出力は引き続き空文字列を返す"""
        output = "調査しました。結果は特にありません。"
        result = _extract_research_report(output)
        assert result == ""


# ---------------------------------------------------------------------------
# Phase 2 Notion 二重保存防止テスト
# ---------------------------------------------------------------------------

class TestPhase2NoNotionDuplicateSave:
    """Phase 2 ノードが Notion に直接保存しないことを検証"""

    def test_no_save_content_to_notion_call(self):
        """phase2_research_node は save_content_to_notion を呼ばない"""
        # phase2_research.py に save_content_to_notion の import がないことを確認
        import hokusai.nodes.phase2_research as mod
        assert not hasattr(mod, "save_content_to_notion"), (
            "phase2_research.py が save_content_to_notion を import しています。"
            "調査レポートの Notion 保存は save_to_subpage_or_create 経由の責務です。"
        )

    def test_no_save_research_to_notion_function(self):
        """_save_research_to_notion ヘルパーが削除されていること"""
        import hokusai.nodes.phase2_research as mod
        assert not hasattr(mod, "_save_research_to_notion"), (
            "_save_research_to_notion が残っています。削除してください。"
        )

    def test_no_extract_child_page_url_function(self):
        """_extract_child_page_url が削除されていること（スキルは書き込み不可）"""
        import hokusai.nodes.phase2_research as mod
        assert not hasattr(mod, "_extract_child_page_url"), (
            "_extract_child_page_url が残っています。"
            "スキルの Notion 書き込みは遮断済みのため不要です。"
        )


# ---------------------------------------------------------------------------
# NotionMCPClient.insert_after_existing: after_marker プロンプト反映テスト
# ---------------------------------------------------------------------------

class TestInsertAfterExistingMarker:
    """after_marker 指定時にマーカーがプロンプトに含まれることを検証"""

    def _make_client(self):
        from hokusai.integrations.notion_mcp import NotionMCPClient
        client = NotionMCPClient()
        mock_claude = MagicMock()
        mock_claude.execute_prompt.return_value = "保存完了"
        client._claude = mock_claude
        return client, mock_claude

    def test_marker_with_ellipsis_in_prompt(self):
        """'...' を含む after_marker がプロンプトに selection_with_ellipsis として反映される"""
        client, mock_claude = self._make_client()
        marker = "::: callout...:::"

        client.insert_after_existing(
            "https://www.notion.so/test-page-aabbccdd11223344aabbccdd11223344",
            "# Test Content",
            after_marker=marker,
        )

        prompt_arg = mock_claude.execute_prompt.call_args[0][0]
        assert "::: callout...:::" in prompt_arg

    def test_marker_without_ellipsis_builds_selection(self):
        """'...' を含まない after_marker から selection_with_ellipsis が構築される"""
        client, mock_claude = self._make_client()
        marker = "some-unique-block-text"

        client.insert_after_existing(
            "https://www.notion.so/test-page-aabbccdd11223344aabbccdd11223344",
            "# Test Content",
            after_marker=marker,
        )

        prompt_arg = mock_claude.execute_prompt.call_args[0][0]
        # [:15]="some-unique-blo", [-15:]="ique-block-text"
        assert "some-unique-blo...ique-block-text" in prompt_arg

    def test_none_marker_uses_append_path(self):
        """after_marker=None は末尾追記パスを使う"""
        client, mock_claude = self._make_client()

        client.insert_after_existing(
            "https://www.notion.so/test-page-aabbccdd11223344aabbccdd11223344",
            "# Test Content",
            after_marker=None,
        )

        prompt_arg = mock_claude.execute_prompt.call_args[0][0]
        assert "末尾" in prompt_arg
        assert "selection_with_ellipsis" not in prompt_arg.split("手順:")[0]

    def test_ambiguous_result_returns_false(self):
        """成功/失敗キーワードがない場合は False を返す（曖昧な成功扱い防止）"""
        client, mock_claude = self._make_client()
        mock_claude.execute_prompt.return_value = "何か別の出力テキスト"

        result = client.insert_after_existing(
            "https://www.notion.so/test-page-aabbccdd11223344aabbccdd11223344",
            "# Test Content",
        )
        assert result is False

    def test_explicit_failure_returns_false(self):
        """明示的な失敗キーワードがある場合は False を返す"""
        client, mock_claude = self._make_client()
        mock_claude.execute_prompt.return_value = "保存失敗: ページが見つかりません"

        result = client.insert_after_existing(
            "https://www.notion.so/test-page-aabbccdd11223344aabbccdd11223344",
            "# Test Content",
        )
        assert result is False


# ---------------------------------------------------------------------------
# Phase 2 disallowed_tools テスト
# ---------------------------------------------------------------------------

class TestPhase2DirectPrompt:
    """Phase 2 が execute_prompt() で直接調査を実行することを検証"""

    def test_notion_write_tools_defined(self):
        """NOTION_WRITE_TOOLS 定数が定義されていること"""
        from hokusai.nodes.phase2_research import NOTION_WRITE_TOOLS
        assert "mcp__notion__notion-update-page" in NOTION_WRITE_TOOLS
        assert "mcp__notion__notion-create-pages" in NOTION_WRITE_TOOLS
        assert "mcp__notion__notion-create-comment" in NOTION_WRITE_TOOLS

    def test_build_prompt_contains_required_elements(self):
        """_build_task_research_prompt が必須要素を含むこと"""
        from hokusai.nodes.phase2_research import _build_task_research_prompt

        prompt = _build_task_research_prompt("https://www.notion.so/test-page")
        # タスクURLが含まれる
        assert "https://www.notion.so/test-page" in prompt
        # 開始見出し強制
        assert "## 事前調査レポート" in prompt
        # 前置き禁止
        assert "前置き" in prompt
        # 必須セクション
        assert "### タスク概要" in prompt
        assert "### 1. 現状" in prompt
        assert "### 2. 関連エンティティ仕様" in prompt
        assert "### 3. 必要な変更" in prompt

    def _build_state(self):
        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        return {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

    @patch("hokusai.nodes.phase2_research._validate_research_output")
    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_uses_execute_prompt_not_execute_skill(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify, mock_verify_content, mock_validate_output,
    ):
        """execute_prompt() が呼ばれ、execute_skill() は呼ばれないこと"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = "## 事前調査レポート\n\nテスト内容"
        mock_claude_cls.return_value = mock_client

        state = self._build_state()
        mock_save.side_effect = lambda s, *a, **kw: s

        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        # execute_prompt が呼ばれること
        mock_client.execute_prompt.assert_called_once()
        # execute_skill は呼ばれないこと
        mock_client.execute_skill.assert_not_called()
        # プロンプトに必須要素が含まれること
        prompt_arg = mock_client.execute_prompt.call_args.kwargs.get("prompt") or mock_client.execute_prompt.call_args[0][0]
        assert "## 事前調査レポート" in prompt_arg
        assert "task-page-aabbccdd" in prompt_arg
        # disallowed_tools が渡されること
        call_kwargs = mock_client.execute_prompt.call_args
        assert call_kwargs.kwargs.get("disallowed_tools") is not None
        assert "mcp__notion__notion-update-page" in call_kwargs.kwargs["disallowed_tools"]


# ---------------------------------------------------------------------------
# Phase 2 fail-fast テスト
# ---------------------------------------------------------------------------

class TestPhase2FailFast:
    """子ページ作成失敗時に Phase 2 が失敗で止まることを検証"""

    def _build_state(self):
        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        return {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

    def test_verify_notion_state_raises_when_no_subpage(self):
        """_verify_notion_state() で phase_subpages[2] 未設定 → RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_notion_state

        state = self._build_state()
        # phase_subpages がない状態
        with pytest.raises(RuntimeError, match="Phase 2 検証失敗"):
            _verify_notion_state(state)

    def test_verify_notion_state_raises_when_empty_subpages(self):
        """_verify_notion_state() で phase_subpages が空辞書 → RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_notion_state

        state = self._build_state()
        state["phase_subpages"] = {}
        with pytest.raises(RuntimeError, match="Phase 2 検証失敗"):
            _verify_notion_state(state)

    def test_verify_notion_state_passes_when_subpage_exists(self):
        """_verify_notion_state() で phase_subpages[2] 設定済み → 正常通過"""
        from hokusai.nodes.phase2_research import _verify_notion_state

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}
        # 例外が発生しないこと
        _verify_notion_state(state)

    @patch("hokusai.nodes.phase2_research._validate_research_output")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_phase2_fails_when_subpage_not_created(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_validate_output,
    ):
        """save_to_subpage_or_create が例外 → Phase 2 FAILED"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = "## 事前調査結果\n\nテスト内容"
        mock_claude_cls.return_value = mock_client

        # save_to_subpage_or_create が RuntimeError を送出
        mock_save.side_effect = RuntimeError("Phase 2 子ページの作成に失敗しました。")

        state = self._build_state()

        from hokusai.nodes.phase2_research import phase2_research_node
        with pytest.raises(RuntimeError, match="子ページの作成に失敗"):
            phase2_research_node(state)

        # Phase 2 が FAILED 状態になっていること
        assert state["phases"][2]["status"] == "failed"

    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_parent_page_never_receives_content(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
    ):
        """save_content_to_notion(task_url, ...) が呼ばれないことを検証"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = "## 事前調査結果\n\nテスト内容"
        mock_claude_cls.return_value = mock_client

        state = self._build_state()
        mock_save.side_effect = lambda s, *a, **kw: s

        with patch("hokusai.nodes.phase2_research.save_to_subpage_or_create") as mock_save2:
            mock_save2.side_effect = lambda s, *a, **kw: s
            with patch("hokusai.nodes.phase2_research._verify_notion_state"):
                with patch("hokusai.nodes.phase2_research._verify_subpage_content"):
                    with patch("hokusai.nodes.phase2_research._validate_research_output"):
                        from hokusai.nodes.phase2_research import phase2_research_node
                        phase2_research_node(state)

        # save_content_to_notion はモジュール内に存在しないことで保証
        import hokusai.nodes.phase2_research as mod
        assert not hasattr(mod, "save_content_to_notion")


# ---------------------------------------------------------------------------
# Phase 2 raw_output 保存テスト
# ---------------------------------------------------------------------------

class TestPhase2RawOutputSave:
    """子ページ保存に raw_output が使用されることを検証"""

    def _build_state(self):
        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        return {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

    @patch("hokusai.nodes.phase2_research._validate_research_output")
    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_saves_raw_output_not_extracted(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify, mock_verify_content, mock_validate_output,
    ):
        """save_to_subpage_or_create にテンプレート化されたページ本文が渡されること"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []

        raw = (
            "調査を開始します。\n\n"
            "## 事前調査結果\n\nテスト内容\n\n"
            "Generated by `/task-research`\n\n"
            "他に質問はありますか？"
        )
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = raw
        mock_claude_cls.return_value = mock_client

        state = self._build_state()
        mock_save.side_effect = lambda s, *a, **kw: s

        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        # save_to_subpage_or_create に渡された content はテンプレート本文
        call_kwargs = mock_save.call_args
        saved_content = call_kwargs.kwargs.get("content") or call_kwargs[0][3]
        assert "# Phase 2: 事前調査" in saved_content
        assert "## 進捗チェックリスト" in saved_content
        assert "## 最新版ドキュメント" in saved_content
        # 最新版ドキュメント内に raw_output が埋め込まれている
        assert raw in saved_content
        # state["research_result"] は抽出後のテキスト（ページ本文とは異なる）
        assert state["research_result"] != raw
        assert "テスト内容" in state["research_result"]


# ---------------------------------------------------------------------------
# Phase 2 本文検証テスト
# ---------------------------------------------------------------------------

class TestVerifySubpageContent:
    """_verify_subpage_content の検証テスト"""

    def _build_state(self):
        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        return {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_passes_when_full_content_saved(self, MockClient):
        """子ページに全文が保存されていれば検証通過"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        raw_output = (
            "## 事前調査結果\n\n"
            "### タスク概要\nユーザー管理で質問一覧表示機能を追加する\n\n"
            "### 影響範囲\nフロントエンドのみ。バックエンドは変更不要。\n\n"
            "### 実装方針\nDataTableコンポーネントを使用して一覧表示する。"
        )
        mock_instance = MagicMock()
        mock_instance.get_page_content.return_value = raw_output
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        # 例外が発生しないこと
        _verify_subpage_content(state, raw_output)

    def test_fails_when_no_subpage_url(self):
        """phase_subpages[2] が未登録 → RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        state = self._build_state()
        with pytest.raises(RuntimeError, match="子ページURLが未登録"):
            _verify_subpage_content(state, "## 事前調査結果\nテスト")

    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_fails_when_content_empty(self, MockClient):
        """子ページ本文が空 → RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        mock_instance = MagicMock()
        mock_instance.get_page_content.return_value = ""
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        with pytest.raises(RuntimeError, match="子ページ本文が空"):
            _verify_subpage_content(state, "## 事前調査結果\nテスト内容テスト内容テスト")

    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_fails_when_summary_only(self, MockClient):
        """子ページがサマリーのみ（同じ見出しがあるが本文短い）→ 長さ比率で検出"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        raw_output = (
            "## 事前調査結果\n\n"
            "### タスク概要\nユーザー管理で質問一覧表示機能を追加する\n\n"
            "### 影響範囲\nフロントエンドのみ。バックエンドは変更不要。\n\n"
            "### 実装方針\nDataTableコンポーネントを使用して一覧表示する。\n\n"
            "### 詳細設計\n既存のUserItemsを参考に実装する。フックはuseSelfIntroductions。"
        )
        # サマリーのみ（見出しは同じだが本文が大幅に短い）
        summary_only = "## 事前調査結果\n\nユーザー管理の質問一覧表示を調査しました。"

        mock_instance = MagicMock()
        mock_instance.get_page_content.return_value = summary_only
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        with pytest.raises(RuntimeError, match="子ページ本文が短すぎます"):
            _verify_subpage_content(state, raw_output)

    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_fails_when_body_anchor_missing(self, MockClient):
        """子ページ本文に中盤アンカーが含まれない → RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        raw_output = (
            "## 事前調査結果\n\n"
            "### タスク概要\nユーザー管理で質問一覧表示機能を追加する\n\n"
            "### 影響範囲\nフロントエンドのみ。バックエンドは変更不要。\n\n"
            "### 実装方針\nDataTableコンポーネントを使用して一覧表示する。"
        )
        # 長さは十分だが中身が異なる（LLMが別の文を生成した場合）
        different_content = (
            "## 事前調査結果\n\n"
            "このタスクについて調査を行いました。結果は以下の通りです。\n"
            "調査の結果、特に問題は見つかりませんでした。実装は容易です。\n"
            "以上が調査結果のまとめになります。詳細は別途共有いたします。\n"
            "追加の調査が必要な場合はお知らせください。対応いたします。"
        )

        mock_instance = MagicMock()
        mock_instance.get_page_content.return_value = different_content
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        with pytest.raises(RuntimeError, match="本文アンカーが見つかりません"):
            _verify_subpage_content(state, raw_output)

    def test_skipped_when_notion_disabled(self, monkeypatch):
        """HOKUSAI_SKIP_NOTION=1 では検証をスキップ"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        monkeypatch.setenv("HOKUSAI_SKIP_NOTION", "1")
        state = self._build_state()
        # phase_subpages がなくてもエラーにならない
        _verify_subpage_content(state, "any content")

    @patch("time.sleep")
    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_retries_on_get_page_content_timeout(self, MockClient, mock_sleep):
        """get_page_content タイムアウト時にリトライして成功する"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        raw_output = (
            "## 事前調査結果\n\n"
            "### タスク概要\nユーザー管理で質問一覧表示機能を追加する\n\n"
            "### 影響範囲\nフロントエンドのみ。バックエンドは変更不要。\n\n"
            "### 実装方針\nDataTableコンポーネントを使用して一覧表示する。"
        )
        mock_instance = MagicMock()
        mock_instance.get_page_content.side_effect = [
            Exception("プロンプトの実行がタイムアウトしました"),
            raw_output,
        ]
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        _verify_subpage_content(state, raw_output)
        assert mock_instance.get_page_content.call_count == 2
        mock_sleep.assert_called_once_with(5)

    @patch("time.sleep")
    @patch("hokusai.integrations.notion_mcp.NotionMCPClient")
    def test_fails_after_max_retries(self, MockClient, mock_sleep):
        """最大リトライ回数を超えると RuntimeError"""
        from hokusai.nodes.phase2_research import _verify_subpage_content

        mock_instance = MagicMock()
        mock_instance.get_page_content.side_effect = Exception("タイムアウト")
        MockClient.return_value = mock_instance

        state = self._build_state()
        state["phase_subpages"] = {2: "https://notion.so/subpage-2"}

        with pytest.raises(RuntimeError, match="3回試行"):
            _verify_subpage_content(state, "## 事前調査結果\nテスト")
        assert mock_instance.get_page_content.call_count == 3
        assert mock_sleep.call_count == 2

    @patch("hokusai.nodes.phase2_research._validate_research_output")
    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_phase2_calls_verify_after_save(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_state, mock_verify_content, mock_validate_output,
    ):
        """phase2_research_node が save 後に _verify_subpage_content を呼ぶこと"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = "## 事前調査結果\n\nテスト内容"
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s

        state = self._build_state()

        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        mock_verify_content.assert_called_once()
        # raw_output が検証に渡されること
        call_args = mock_verify_content.call_args
        assert call_args[0][0] is state
        assert "## 事前調査結果" in call_args[0][1]

    @patch("hokusai.nodes.phase2_research._validate_research_output")
    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_phase2_fails_when_verify_content_fails(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_content, mock_validate_output,
    ):
        """_verify_subpage_content 失敗時に Phase 2 が失敗すること"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.return_value = "## 事前調査結果\n\nテスト内容"
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s
        mock_verify_content.side_effect = RuntimeError("Phase 2 本文検証失敗: 子ページ本文が空です。")

        state = self._build_state()

        from hokusai.nodes.phase2_research import phase2_research_node
        with pytest.raises(RuntimeError, match="本文検証失敗"):
            phase2_research_node(state)

        assert state["phases"][2]["status"] == "failed"


# ---------------------------------------------------------------------------
# _pick_body_anchor テスト
# ---------------------------------------------------------------------------

class TestPickBodyAnchor:
    """_pick_body_anchor のロジック検証"""

    def test_picks_middle_content_line(self):
        """本文中盤の非見出し行を選択する"""
        from hokusai.nodes.phase2_research import _pick_body_anchor

        raw = (
            "## 事前調査結果\n"
            "### タスク概要\n"
            "ユーザー管理で質問一覧表示機能を追加する\n"
            "### 影響範囲\n"
            "フロントエンドのみ。バックエンドは変更不要。\n"
            "### 実装方針\n"
            "DataTableコンポーネントを使用して一覧表示する。"
        )
        anchor = _pick_body_anchor(raw)
        # 見出し行は選ばれない
        assert anchor is not None
        assert not anchor.startswith("#")
        assert len(anchor) >= 10

    def test_skips_headings_and_short_lines(self):
        """見出し行と短い行はスキップされる"""
        from hokusai.nodes.phase2_research import _pick_body_anchor

        raw = "## 見出し\n短い\n### 別の見出し\nこれは十分に長い本文コンテンツ行です。"
        anchor = _pick_body_anchor(raw)
        assert anchor == "これは十分に長い本文コンテンツ行です。"

    def test_returns_none_for_headings_only(self):
        """見出しのみの場合は None"""
        from hokusai.nodes.phase2_research import _pick_body_anchor

        raw = "## 見出し1\n### 見出し2\n## 見出し3"
        assert _pick_body_anchor(raw) is None

    def test_returns_none_for_empty(self):
        """空文字列の場合は None"""
        from hokusai.nodes.phase2_research import _pick_body_anchor

        assert _pick_body_anchor("") is None


# ---------------------------------------------------------------------------
# _validate_research_output テスト
# ---------------------------------------------------------------------------

class TestValidateResearchOutput:
    """raw_output の品質検証（サマリー出力を正本として保存しないためのガード）"""

    FULL_REPORT = (
        "## 事前調査レポート\n\n"
        "### タスク概要\n"
        "**タスク名:** ユーザー管理で質問一覧表示\n"
        "**タスク種別:** 新規機能\n\n"
        "---\n\n"
        "### 1. 現状\n"
        "| 項目 | 状態 |\n|------|------|\n"
        "| 一覧表示 | 未実装 |\n\n"
        "---\n\n"
        "### 2. 関連エンティティ仕様\n"
        "| 項目 | 内容 |\n|------|------|\n"
        "| 型 | SelfIntroductionDocument |\n\n"
        "---\n\n"
        "### 3. 必要な変更\n"
        "| レイヤー | ファイル | 変更内容 |\n"
        "|----------|----------|----------|\n"
        "| フロントエンド | UserQuestions.tsx | 新規作成 |\n"
    )

    def test_full_report_passes(self):
        """フルレポート出力は検証を通過する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        _validate_research_output(self.FULL_REPORT)

    def test_full_report_with_3_sections_passes(self):
        """必須セクション 3/4 でも検証を通過する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        # ### 3. 必要な変更 を除外（3セクションのみ）
        report = (
            "## 事前調査レポート\n\n"
            "### タスク概要\nテストタスク\n\n"
            "### 1. 現状\n実装済み\n\n"
            "### 2. 関連エンティティ仕様\nDocument型\n"
        )
        _validate_research_output(report)

    def test_summary_only_fails(self):
        """サマリーのみの出力は fail する（許可開始見出しでもない）"""
        from hokusai.nodes.phase2_research import _validate_research_output

        summary = (
            "### 調査結果のサマリー\n\n"
            "**タスク:** ユーザー管理で質問一覧表示\n\n"
            "調査の結果、バックエンドは実装済みでフロントのみ変更が必要です。\n"
        )
        with pytest.raises(RuntimeError, match="許可開始見出しで始まっていません"):
            _validate_research_output(summary)

    def test_preface_plus_summary_fails(self):
        """前置き + サマリーの出力は fail する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        output = (
            "事前調査が完了しました。以下が調査結果です。\n\n"
            "### 調査結果のサマリー\n\n"
            "バックエンドは実装済みです。フロントエンドのみ変更が必要です。\n"
        )
        with pytest.raises(RuntimeError, match="許可開始見出しで始まっていません"):
            _validate_research_output(output)

    def test_preface_plus_full_report_fails(self):
        """前置き文 + フルレポートでも fail する（raw_output は本文のみであるべき）"""
        from hokusai.nodes.phase2_research import _validate_research_output

        output = "了解しました。事前調査を開始します。\n\n" + self.FULL_REPORT
        with pytest.raises(RuntimeError, match="許可開始見出しで始まっていません"):
            _validate_research_output(output)

    def test_meta_explanation_notion_paste_fails(self):
        """「手動でNotionに貼り付けてください」を含む出力は fail する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        output = self.FULL_REPORT + "\n手動でNotionに貼り付けてください。\n"
        with pytest.raises(RuntimeError, match="禁止メタ説明"):
            _validate_research_output(output)

    def test_meta_explanation_notion_mcp_fails(self):
        """「Notion MCPにはページコンテンツ更新ツールがない」を含む出力は fail する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        output = self.FULL_REPORT + "\nNotion MCPにはページコンテンツ更新ツールがないため、手動で行ってください。\n"
        with pytest.raises(RuntimeError, match="禁止メタ説明"):
            _validate_research_output(output)

    def test_only_2_sections_fails(self):
        """必須セクション 2/4 以下は fail する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        output = (
            "## 事前調査レポート\n\n"
            "### タスク概要\nテストタスク\n\n"
            "### 1. 現状\n実装済み\n"
        )
        with pytest.raises(RuntimeError, match="必須セクションが不足"):
            _validate_research_output(output)

    def test_empty_output_fails(self):
        """空出力は fail する"""
        from hokusai.nodes.phase2_research import _validate_research_output

        with pytest.raises(RuntimeError, match="raw_output が空"):
            _validate_research_output("")

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_phase2_stops_before_save_on_validation_failure(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_content,
    ):
        """2回とも検証失敗時に保存前に停止する"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        # 1回目も2回目もサマリーのみの出力
        mock_client.execute_prompt.return_value = "### 調査結果のサマリー\nバックエンドは実装済み。"
        mock_claude_cls.return_value = mock_client

        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        state = {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

        from hokusai.nodes.phase2_research import phase2_research_node
        with pytest.raises(RuntimeError, match="出力検証失敗"):
            phase2_research_node(state)

        # 2回 execute_prompt が呼ばれること（初回 + 再生成）
        assert mock_client.execute_prompt.call_count == 2
        # save_to_subpage_or_create は呼ばれていないこと
        mock_save.assert_not_called()
        # Phase 2 が FAILED 状態になっていること
        assert state["phases"][2]["status"] == "failed"


# ---------------------------------------------------------------------------
# Phase 2 再生成（retry）テスト
# ---------------------------------------------------------------------------

class TestPhase2OutputRetry:
    """Phase 2 出力検証失敗時の 1 回だけ再生成テスト"""

    FULL_REPORT = (
        "## 事前調査レポート\n\n"
        "### タスク概要\nテストタスク\n\n"
        "### 1. 現状\n実装済み\n\n"
        "### 2. 関連エンティティ仕様\nDocument型\n\n"
        "### 3. 必要な変更\nフロントエンドのみ\n"
    )

    def _build_state(self):
        phase_template = {
            "status": "pending",
            "started_at": None,
            "completed_at": None,
            "error_message": None,
            "retry_count": 0,
        }
        return {
            "task_url": "https://www.notion.so/task-page-aabbccdd",
            "task_name": "テストタスク",
            "repo_path": "/tmp/test",
            "workflow_id": "test-wf-001",
            "phases": {i: {**phase_template} for i in range(1, 11)},
            "audit_log": [],
            "schema_change_required": False,
            "research_result": "",
        }

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_retry_succeeds_after_preface(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_state, mock_verify_content,
    ):
        """初回が前置き文付き、2回目が正常 → 2回目の出力を含むテンプレート本文が保存される"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        preface_output = "調査完了しました。レポートを出力します。\n\n" + self.FULL_REPORT
        mock_client.execute_prompt.side_effect = [preface_output, self.FULL_REPORT]
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s

        state = self._build_state()
        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        # 2回 execute_prompt が呼ばれる
        assert mock_client.execute_prompt.call_count == 2
        # 保存されるのは 2回目の出力を埋め込んだテンプレート本文
        saved_content = mock_save.call_args.kwargs.get("content") or mock_save.call_args[0][3]
        assert "# Phase 2: 事前調査" in saved_content
        assert self.FULL_REPORT in saved_content
        assert "調査完了しました。レポートを出力します。" not in saved_content
        # audit_log に retry 記録が残る
        retry_logs = [
            log for log in state["audit_log"]
            if log.get("action") == "research_output_retry"
        ]
        assert len(retry_logs) == 1
        assert retry_logs[0]["details"]["attempt"] == 2

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_retry_both_fail(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_content,
    ):
        """初回も2回目も前置き文付き → 2回目で RuntimeError"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        bad_output = "事前調査が完了しました。\n\n### 調査結果のサマリー\nテスト"
        mock_client.execute_prompt.return_value = bad_output
        mock_claude_cls.return_value = mock_client

        state = self._build_state()
        from hokusai.nodes.phase2_research import phase2_research_node
        with pytest.raises(RuntimeError, match="出力検証失敗"):
            phase2_research_node(state)

        assert mock_client.execute_prompt.call_count == 2
        mock_save.assert_not_called()

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_retry_empty_then_success(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_state, mock_verify_content,
    ):
        """初回が空出力、2回目が正常 → retry 後に成功"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        mock_client.execute_prompt.side_effect = ["", self.FULL_REPORT]
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s

        state = self._build_state()
        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        assert mock_client.execute_prompt.call_count == 2
        assert state["phases"][2]["status"] == "completed"

    def test_retry_prompt_contains_previous_output_and_error(self):
        """_build_research_retry_prompt に task_url, previous_output, validation_error が含まれる"""
        from hokusai.nodes.phase2_research import _build_research_retry_prompt

        prompt = _build_research_retry_prompt(
            task_url="https://www.notion.so/task-page-aabbccdd",
            previous_output="調査完了しました。レポートを出力します。",
            validation_error="Phase 2 出力検証失敗: 許可開始見出しで始まっていません。",
        )
        # 元タスクURLが含まれる
        assert "https://www.notion.so/task-page-aabbccdd" in prompt
        # 前回出力が含まれる
        assert "調査完了しました。レポートを出力します。" in prompt
        # エラーメッセージが含まれる
        assert "許可開始見出しで始まっていません" in prompt
        # 再生成ルールが含まれる
        assert "## 事前調査レポート" in prompt
        assert "前置き文" in prompt
        assert "全文" in prompt
        # 元の調査手順が含まれる
        assert "mcp__notion__notion-fetch" in prompt
        assert "### タスク概要" in prompt
        assert "### 1. 現状" in prompt

    def test_retry_prompt_includes_full_previous_output(self):
        """_build_research_retry_prompt が前回出力を切り詰めずに全文含めること"""
        from hokusai.nodes.phase2_research import _build_research_retry_prompt

        # 3000文字超の前回出力
        long_output = "調査完了しました。\n" + "セクション内容 " * 500
        assert len(long_output) > 2000

        prompt = _build_research_retry_prompt(
            task_url="https://www.notion.so/test",
            previous_output=long_output,
            validation_error="テストエラー",
        )
        # 全文が含まれる（切り詰めなし）
        assert long_output in prompt

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_retry_success_passes_retried_output_to_cross_review(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_state, mock_verify_content,
    ):
        """retry 後成功時、cross_review へ渡る文書も再生成後の内容"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        preface_output = "全ての調査が完了しました。\n\n" + self.FULL_REPORT
        mock_client.execute_prompt.side_effect = [preface_output, self.FULL_REPORT]
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s

        state = self._build_state()
        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        # cross_review に渡されたドキュメントが再生成後の研究レポート（抽出後）であること
        cross_review_doc = mock_cross_review.call_args[0][1]
        assert "全ての調査が完了しました" not in cross_review_doc
        assert "## 事前調査レポート" in cross_review_doc

    @patch("hokusai.nodes.phase2_research._verify_subpage_content")
    @patch("hokusai.nodes.phase2_research._verify_notion_state")
    @patch("hokusai.nodes.phase2_research.execute_cross_review", side_effect=lambda s, *a, **kw: s)
    @patch("hokusai.nodes.phase2_research.save_to_subpage_or_create")
    @patch("hokusai.nodes.phase2_research.get_config")
    @patch("hokusai.nodes.phase2_research.ClaudeCodeClient")
    def test_retry_success_status_completed(
        self, mock_claude_cls, mock_config, mock_save, mock_cross_review,
        mock_verify_state, mock_verify_content,
    ):
        """retry 後成功した場合に phases[2].status == completed"""
        mock_config.return_value.skill_timeout = 300
        mock_config.return_value.schema_change_keywords = []
        mock_client = MagicMock()
        preface_output = "調査完了しました。レポートを出力します。\n\n" + self.FULL_REPORT
        mock_client.execute_prompt.side_effect = [preface_output, self.FULL_REPORT]
        mock_claude_cls.return_value = mock_client
        mock_save.side_effect = lambda s, *a, **kw: s

        state = self._build_state()
        from hokusai.nodes.phase2_research import phase2_research_node
        phase2_research_node(state)

        assert state["phases"][2]["status"] == "completed"


# ---------------------------------------------------------------------------
# ClaudeCodeClient.execute_prompt disallowed_tools テスト
# ---------------------------------------------------------------------------

class TestExecutePromptDisallowedTools:
    """execute_prompt の disallowed_tools が CLI に正しく渡されることを検証"""

    @patch("hokusai.integrations.claude_code.ShellRunner")
    @patch("hokusai.integrations.claude_code.get_config")
    def test_disallowed_tools_passed_to_cli(self, mock_config, MockShellRunner):
        """disallowed_tools が --disallowed-tools フラグとして渡される"""
        from hokusai.integrations.claude_code import ClaudeCodeClient

        mock_config.return_value.project_root = Path("/tmp/test")
        mock_shell = MagicMock()
        mock_result = MagicMock()
        mock_result.success = True
        mock_result.stdout = "## 事前調査レポート\n\nテスト"
        mock_shell.run.return_value = mock_result
        MockShellRunner.return_value = mock_shell

        with patch.object(ClaudeCodeClient, "_find_claude_command", return_value="/usr/bin/claude"):
            client = ClaudeCodeClient()
            client.execute_prompt(
                prompt="調査してください",
                allow_mcp_tools=True,
                allow_file_operations=True,
                disallowed_tools=["mcp__notion__notion-update-page", "mcp__notion__notion-create-pages"],
            )

        cmd = mock_shell.run.call_args[0][0]
        assert "--disallowed-tools" in cmd
        idx = cmd.index("--disallowed-tools")
        assert "mcp__notion__notion-update-page" in cmd[idx + 1]
        assert "mcp__notion__notion-create-pages" in cmd[idx + 1]

    @patch("hokusai.integrations.claude_code.ShellRunner")
    @patch("hokusai.integrations.claude_code.get_config")
    def test_no_disallowed_tools_by_default(self, mock_config, MockShellRunner):
        """disallowed_tools=None では --disallowed-tools が付かない"""
        from hokusai.integrations.claude_code import ClaudeCodeClient

        mock_config.return_value.project_root = Path("/tmp/test")
        mock_shell = MagicMock()
        mock_result = MagicMock()
        mock_result.success = True
        mock_result.stdout = "plan output"
        mock_shell.run.return_value = mock_result
        MockShellRunner.return_value = mock_shell

        with patch.object(ClaudeCodeClient, "_find_claude_command", return_value="/usr/bin/claude"):
            client = ClaudeCodeClient()
            client.execute_prompt(prompt="テスト")

        cmd = mock_shell.run.call_args[0][0]
        assert "--disallowed-tools" not in cmd
