"""
output_parser のテスト

検証項目:
- extract_markdown_section: 完全一致 / プレフィックスマッチ / 未検出
- _find_prefix_heading: 双方向プレフィックスマッチ / 誤マッチ防止
"""

from hokusai.utils.output_parser import (
    extract_markdown_section,
    _find_prefix_heading,
    _strip_heading_prefix,
)


# === extract_markdown_section ===


class TestExtractMarkdownSection:
    """Markdownセクション抽出の基本テスト"""

    def test_exact_match(self):
        """完全一致で抽出"""
        output = "前文\n\n## レポート\n\n内容\n\nGenerated by skill"
        result = extract_markdown_section(
            output,
            start_markers=["## レポート"],
            end_markers=["Generated by"],
        )
        assert "## レポート" in result
        assert "内容" in result
        assert "前文" not in result

    def test_no_match_returns_original(self):
        """マーカー未検出時は元テキストを返す"""
        output = "何もマーカーがない文章です。"
        result = extract_markdown_section(output, start_markers=["## レポート"])
        assert result == output

    def test_prefix_match_shorter_heading(self):
        """出力の見出しがマーカーより短い場合（長音省略等）"""
        output = "前文\n\n## 調査結果サマリ\n\n内容\n\nGenerated by skill"
        result = extract_markdown_section(
            output,
            start_markers=["## 調査結果サマリー"],
            end_markers=["Generated by"],
        )
        assert "内容" in result
        assert "前文" not in result

    def test_prefix_match_longer_heading(self):
        """出力の見出しがマーカーより長い場合（接尾辞付き）"""
        output = "前文\n\n## 事前調査レポート（概要）\n\n内容"
        result = extract_markdown_section(
            output,
            start_markers=["## 事前調査レポート"],
        )
        assert "内容" in result
        assert "前文" not in result

    def test_exact_takes_priority_over_prefix(self):
        """完全一致がある場合はプレフィックスマッチより優先"""
        output = (
            "## 調査結果サマリ\n偽物\n\n"
            "## 調査結果サマリー\n本物\n\n"
            "Generated by skill"
        )
        result = extract_markdown_section(
            output,
            start_markers=["## 調査結果サマリー"],
            end_markers=["Generated by"],
        )
        assert "本物" in result

    def test_multiple_markers_first_match_wins(self):
        """複数マーカーの場合、最初にマッチしたものを使用"""
        output = "前文\n\n## 事前調査結果\n\n内容A"
        result = extract_markdown_section(
            output,
            start_markers=["## 事前調査結果", "## 事前調査レポート"],
        )
        assert "内容A" in result

    def test_heading_level_change(self):
        """見出しレベルが ## → ### に変わってもプレフィックスマッチで抽出"""
        output = "前文\n\n### 事前調査レポート\n\n内容\n\nGenerated by skill"
        result = extract_markdown_section(
            output,
            start_markers=["## 事前調査レポート"],
            end_markers=["Generated by"],
        )
        assert "内容" in result
        assert "前文" not in result

    def test_end_marker_terminates_section(self):
        """終了マーカーでセクションが終了"""
        output = "## レポート\n内容\nGenerated by skill\n後続テキスト"
        result = extract_markdown_section(
            output,
            start_markers=["## レポート"],
            end_markers=["Generated by"],
        )
        assert "内容" in result
        assert "後続テキスト" not in result


# === _find_prefix_heading ===


class TestFindPrefixHeading:
    """プレフィックスマッチのテスト"""

    def test_exact_match(self):
        """完全一致"""
        output = "## 事前調査レポート\n内容"
        result = _find_prefix_heading(output, ["## 事前調査レポート"])
        assert result == "## 事前調査レポート"

    def test_heading_shorter_than_marker(self):
        """見出しがマーカーより1文字短い（長音省略）"""
        output = "## 調査結果サマリ\n内容"
        result = _find_prefix_heading(output, ["## 調査結果サマリー"])
        assert result == "## 調査結果サマリ"

    def test_heading_longer_than_marker(self):
        """見出しがマーカーより長い（接尾辞付き）"""
        output = "## 事前調査レポート（概要）\n内容"
        result = _find_prefix_heading(output, ["## 事前調査レポート"])
        assert result == "## 事前調査レポート（概要）"

    def test_heading_level_mismatch(self):
        """見出しレベルが異なっても（## vs ###）テキスト部分でマッチ"""
        output = "### 事前調査レポート\n内容"
        result = _find_prefix_heading(output, ["## 事前調査レポート"])
        assert result == "### 事前調査レポート"

    def test_heading_level_h3_to_h2(self):
        """### マーカーで ## 見出しにもマッチ"""
        output = "## 事前調査結果\n内容"
        result = _find_prefix_heading(output, ["### 事前調査結果"])
        assert result == "## 事前調査結果"

    def test_too_short_no_match(self):
        """テキスト部分が2文字未満の見出しはマッチしない"""
        output = "## X\n内容"
        result = _find_prefix_heading(output, ["## Xyz"])
        assert result is None

    def test_ratio_too_low_no_match(self):
        """一致比率が低すぎる場合はマッチしない"""
        output = "## 調査\n内容"
        result = _find_prefix_heading(output, ["## 調査結果サマリー"])
        assert result is None

    def test_non_heading_line_ignored(self):
        """# で始まらない行は無視"""
        output = "調査結果サマリー\n\n## 別の見出し"
        result = _find_prefix_heading(output, ["## 調査結果サマリー"])
        assert result is None  # 本文行はマッチしない

    def test_multiple_markers(self):
        """複数マーカーの最初にマッチしたものを返す"""
        output = "## 調査結果サマリ\n内容"
        result = _find_prefix_heading(
            output, ["## 事前調査結果", "## 調査結果サマリー"]
        )
        assert result == "## 調査結果サマリ"
