"""
出力パーサーユーティリティ

Claude Codeスキル出力からMarkdownセクションを抽出する共通関数を提供する。
"""

import re


def extract_markdown_section(
    output: str,
    start_markers: list[str],
    end_markers: list[str] | None = None,
) -> str:
    """
    スキル出力から特定のMarkdownセクションを抽出する。

    Claude Codeの出力にはレポート以外の会話テキスト
    （例: 「他に作業が必要なタスクはありますか？」）が含まれる場合がある。
    これらを除外し、指定されたセクション部分のみを返す。

    抽出ロジック:
    1. start_markers の完全一致で抽出を試行
    2. 完全一致なしの場合、プレフィックスマッチで見出しを検索
    3. いずれも見つからない場合は元の出力をそのまま返す

    Args:
        output: スキルの生出力テキスト
        start_markers: セクション開始を示すマーカー文字列のリスト
            （例: ["## 事前調査結果"]）
        end_markers: セクション終了を示すマーカー文字列のリスト
            （例: ["Generated by"]）。Noneの場合は終了マーカーなし。

    Returns:
        抽出されたセクションのテキスト。見つからない場合は元の出力をそのまま返す。
    """
    if end_markers is None:
        end_markers = []

    # Phase 1: 完全一致
    for start_marker in start_markers:
        result = _extract_with_marker(output, start_marker, end_markers)
        if result is not None:
            return result

    # Phase 2: プレフィックスマッチ — 出力内の見出しがマーカーと前方一致するか確認
    actual_heading = _find_prefix_heading(output, start_markers)
    if actual_heading:
        result = _extract_with_marker(output, actual_heading, end_markers)
        if result is not None:
            return result

    # いずれのマーカーも見つからない場合は元の出力を返す
    return output


def _extract_with_marker(
    output: str,
    start_marker: str,
    end_markers: list[str],
) -> str | None:
    """指定マーカーでセクションを抽出。見つからなければ None。"""
    escaped_start = re.escape(start_marker)

    # 1. start_marker から end_marker までの範囲を正規表現で抽出
    for end_marker in end_markers:
        escaped_end = re.escape(end_marker)
        match = re.search(
            rf"({escaped_start}[\s\S]*?{escaped_end}[^\n]*)",
            output,
            re.MULTILINE,
        )
        if match:
            return match.group(1).strip()

    # 2. フォールバック: start_marker 以降を全て取得
    match = re.search(rf"({escaped_start}[\s\S]*)", output, re.MULTILINE)
    if match:
        content = match.group(1).strip()
        # end_markers が指定されている場合、最初に見つかった行で終了
        if end_markers:
            lines = content.split("\n")
            result_lines = []
            for line in lines:
                result_lines.append(line)
                if any(marker in line for marker in end_markers):
                    break
            return "\n".join(result_lines)
        return content

    return None


def _strip_heading_prefix(text: str) -> str:
    """Markdown見出しの '#' プレフィックスとスペース、先頭の絵文字/記号を除去してテキスト部分のみ返す。

    例: "## 事前調査結果" → "事前調査結果"
        "### 調査結果のサマリー" → "調査結果のサマリー"
        "## 🔍 設計チェック結果" → "設計チェック結果"
    """
    text = re.sub(r'^#+\s*', '', text)
    text = re.sub(r'^[^\w]+', '', text)
    return text


def _find_prefix_heading(
    output: str,
    markers: list[str],
    min_ratio: float = 0.8,
) -> str | None:
    """出力内のMarkdown見出しとマーカーの双方向プレフィックスマッチ。

    見出しがマーカーの先頭と一致するか、マーカーが見出しの先頭と一致する場合にマッチ。
    LLMの出力ヘッダー揺れ（長音省略、表記ゆれ、見出しレベル変更等）を吸収する。

    比較時は見出しレベル（## vs ###）を無視し、テキスト部分のみで照合する。

    Args:
        output: スキルの生出力テキスト
        markers: マーカー文字列のリスト
        min_ratio: 最短文字列長 / 最長文字列長 の最低比率（デフォルト 0.8）

    Returns:
        マッチした見出し文字列。見つからなければ None。
    """
    for line in output.split("\n"):
        stripped = line.strip()
        if not stripped.startswith("#"):
            continue
        heading_text = _strip_heading_prefix(stripped)
        for marker in markers:
            marker_text = _strip_heading_prefix(marker)

            # 短い方が2文字未満なら誤マッチ防止でスキップ
            shorter = min(len(heading_text), len(marker_text))
            if shorter < 2:
                continue

            if heading_text.startswith(marker_text):
                # 見出しがマーカーで始まる（見出しのほうが長い or 同じ）
                return stripped

            if marker_text.startswith(heading_text):
                # マーカーが見出しで始まる（見出しのほうが短い = LLM省略）
                longer = max(len(heading_text), len(marker_text))
                if shorter / longer >= min_ratio:
                    return stripped

    return None
