"""
Phase 3: 設計チェック

- 直接プロンプトで設計チェックを実行（Notion書き込みツール遮断）
- Phase 2の調査結果と cross-review 指摘をコンテキストとして注入
- 設計チェック結果をNotionに子ページとして保存（hokusaiが唯一の書き込み経路）

Note:
    直接プロンプト実行により出力フォーマットを hokusai 側で完全制御する。
    Notion 書き込みは --disallowed-tools で遮断。
"""

import os

from ..config import get_config
from ..integrations.claude_code import ClaudeCodeClient
from ..logging_config import get_logger
from ..state import (
    PhaseStatus,
    WorkflowState,
    add_audit_log,
    should_skip_phase,
    update_phase_status,
)
from ..utils.cross_review import execute_cross_review, format_cross_review_for_prompt
from ..utils.notion_helpers import save_to_subpage_or_create
from ..utils.output_parser import _find_prefix_heading, extract_markdown_section
from ..utils.phase_page_templates import (
    build_phase_page_content,
    initialize_phase_page_state,
)

logger = get_logger("phase3")

# 設計チェック実行時に遮断する Notion 書き込み系ツール
NOTION_WRITE_TOOLS = [
    "mcp__notion__notion-update-page",
    "mcp__notion__notion-create-pages",
    "mcp__notion__notion-create-comment",
    "mcp__notion__notion-update-data-source",
    "mcp__notion__notion-create-database",
    "mcp__notion__notion-move-pages",
    "mcp__notion__notion-duplicate-page",
]


def _extract_design_check_content(output: str) -> str:
    """直接プロンプト出力から設計チェック部分を抽出"""
    result = extract_markdown_section(
        output,
        start_markers=_DESIGN_START_MARKERS,
        end_markers=["Generated by"],
    )
    if result == output:
        if _find_prefix_heading(output, _DESIGN_START_MARKERS):
            return result
        logger.warning(
            "設計チェックの抽出マーカーが見つかりません（保存スキップ）: "
            f"出力先頭={output[:80]!r}"
        )
        return ""
    return result


def phase3_design_node(state: WorkflowState) -> WorkflowState:
    """Phase 3: 設計チェック

    - Phase 2の調査結果(research_result)を直接プロンプトで設計チェック
    - Phase 2のクロスLLMレビュー指摘事項をコンテキストとして注入
    - research_resultがない場合はパススルー
    """

    if should_skip_phase(state, 3):
        print("⏭️  Phase 3 スキップ: 設計済み")
        return state

    state = update_phase_status(state, 3, PhaseStatus.IN_PROGRESS)

    try:
        research_result = state.get("research_result")

        if not research_result:
            logger.debug("Phase 3: research_result なし - パススルー")
            state = add_audit_log(
                state, 3, "design_skipped", "info",
                {"reason": "no_research_result"},
            )
            state = update_phase_status(state, 3, PhaseStatus.COMPLETED)
            print("✅ Phase 3 完了（調査結果なし: スキップ）")
            return state

        config = get_config()
        claude = ClaudeCodeClient()

        # [1/3] 直接プロンプトで設計チェックを実行（Notion書き込み遮断）
        print("📋 Phase 3 [1/3] 設計チェック実行中...")
        cross_review_context = format_cross_review_for_prompt(state, source_phase=2)
        design_prompt = _build_design_check_prompt(
            task_url=state["task_url"],
            research_result=research_result,
            cross_review_context=cross_review_context,
        )
        if cross_review_context:
            logger.info(f"直接プロンプトで設計チェックを実行: {state['task_url']} (+Phase 2 クロスレビュー指摘)")
        else:
            logger.info(f"直接プロンプトで設計チェックを実行: {state['task_url']}")

        raw_output = claude.execute_prompt(
            prompt=design_prompt,
            timeout=config.skill_timeout,
            allow_mcp_tools=True,
            allow_file_operations=True,
            disallowed_tools=NOTION_WRITE_TOOLS,
        )

        # 設計チェック出力を抽出
        output_text = _extract_design_check_content(raw_output)
        logger.debug(f"design-check出力: {len(raw_output)}文字 → 抽出後: {len(output_text)}文字")

        # raw_output がフルレポートであることを検証（サマリー出力を正本として保存しない）
        # 検証失敗時は 1 回だけ再生成を試みる
        try:
            _validate_design_output(raw_output)
        except RuntimeError as e:
            logger.warning(f"Phase 3 初回出力が検証失敗、再生成を試みます: {e}")
            state = add_audit_log(
                state, 3, "design_output_retry", "warning",
                details={
                    "reason": str(e),
                    "attempt": 2,
                    "first_output_length": len(raw_output) if raw_output else 0,
                },
            )
            print("📋 Phase 3 [1/3] 出力検証失敗、再生成中...")
            retry_prompt = _build_design_retry_prompt(
                task_url=state["task_url"],
                research_result=research_result,
                previous_output=raw_output,
                validation_error=str(e),
                cross_review_context=cross_review_context,
            )
            raw_output = claude.execute_prompt(
                prompt=retry_prompt,
                timeout=config.skill_timeout,
                allow_mcp_tools=True,
                allow_file_operations=True,
                disallowed_tools=NOTION_WRITE_TOOLS,
            )
            output_text = _extract_design_check_content(raw_output)
            logger.debug(f"design-check再生成出力: {len(raw_output)}文字 → 抽出後: {len(output_text)}文字")
            # 2回目も失敗した場合は fail-fast
            _validate_design_output(raw_output)
            logger.info("Phase 3 再生成で出力検証を通過しました")

        # Phase page metadata を初期化（表示状態はテンプレート側で導出）
        initialize_phase_page_state(state, 3)

        phase_page_content = build_phase_page_content(
            state=state,
            phase=3,
            latest_document=raw_output,
            source_phase="phase3_design",
        )

        # [2/3] Notionに設計チェック結果を子ページとして保存
        print("📋 Phase 3 [2/3] 子ページ保存中...")
        state = save_to_subpage_or_create(
            state, state["task_url"], phase=3, content=phase_page_content,
            workflow_id=state.get("workflow_id", ""),
        )

        # state に設計チェック結果を保存（cross-review fix loop 用）
        state["design_result"] = raw_output

        # 保存後検証: 子ページ本文が空でなく、アンカーを含むことを確認
        # 検証失敗は警告のみ（設計チェック自体は完了しているため致命的にしない）
        try:
            _verify_design_subpage_content(state, raw_output)
        except RuntimeError as e:
            logger.warning(f"子ページ保存後検証失敗（続行）: {e}")
            print(f"⚠️  {e}")

        # [3/3] Codex クロスレビュー（設定で有効時のみ）
        # 子ページ作成後に実行することで、callout が子ページに保存される
        print("📋 Phase 3 [3/3] クロスレビュー...")
        review_document = output_text or research_result
        state = execute_cross_review(state, review_document, phase=3)

        if state.get("waiting_for_human"):
            state = update_phase_status(state, 3, PhaseStatus.FAILED, "cross_review_blocked")
            state = add_audit_log(
                state, 3, "cross_review_blocked", "failed",
                details={"reason": state.get("human_input_request")},
            )
            print("🛑 Phase 3 停止: クロスLLMレビューで確認が必要です")
            return state

        state = update_phase_status(state, 3, PhaseStatus.COMPLETED)
        state = add_audit_log(state, 3, "design_completed", "success", {
            "design_check_length": len(output_text),
            "cross_review_context_injected": bool(cross_review_context),
        })
        print("✅ Phase 3 完了: 設計チェックが完了しました")
        return state

    except Exception as e:
        state = update_phase_status(state, 3, PhaseStatus.FAILED, str(e))
        state = add_audit_log(state, 3, "phase_failed", "error", error=str(e))
        print(f"❌ Phase 3 失敗: {e}")
        raise


# ---------------------------------------------------------------------------
# 出力品質検証
# ---------------------------------------------------------------------------

_DESIGN_START_MARKERS = [
    "## 設計チェック",
    "## 設計レビュー",
    "## Design Check",
]

_DESIGN_REQUIRED_SECTIONS = [
    "### 概要",
    "### 設計方針",
    "### リスク",
    "### 確認事項",
]

_FORBIDDEN_META_PHRASES = [
    "手動でNotionに貼り付け",
    "Notion MCPにはページコンテンツ更新ツールがない",
    "手動で貼り付けてください",
    "Notion追記について",
]


def _validate_design_output(raw_output: str) -> None:
    """raw_output がフルレポートであることを検証

    検証条件:
    1. 許可開始見出しで始まること
    2. 必須セクション見出しを 4 つ中 3 つ以上含むこと
    3. 禁止メタ説明を含まないこと

    失敗時は RuntimeError を送出し、Phase 3 を fail-fast にする。
    """
    if not raw_output or not raw_output.strip():
        raise RuntimeError(
            "Phase 3 出力検証失敗: raw_output が空です。"
        )

    stripped = raw_output.strip()
    starts_with_marker = any(stripped.startswith(m) for m in _DESIGN_START_MARKERS)
    if not starts_with_marker:
        first_line = stripped.split("\n", 1)[0][:80]
        raise RuntimeError(
            f"Phase 3 出力検証失敗: 許可開始見出しで始まっていません。"
            f" 先頭行={first_line!r}"
        )

    for phrase in _FORBIDDEN_META_PHRASES:
        if phrase in raw_output:
            raise RuntimeError(
                f"Phase 3 出力検証失敗: 禁止メタ説明を含んでいます。"
                f" phrase={phrase!r}"
            )

    section_count = sum(1 for s in _DESIGN_REQUIRED_SECTIONS if s in raw_output)
    if section_count < 3:
        raise RuntimeError(
            f"Phase 3 出力検証失敗: フルレポートの必須セクションが不足しています。"
            f" 必須セクション={section_count}/4 (閾値=3)"
        )

    logger.info(f"Phase 3 出力検証OK: 必須セクション={section_count}/4")


# ---------------------------------------------------------------------------
# 保存後検証
# ---------------------------------------------------------------------------

def _verify_design_subpage_content(state: WorkflowState, raw_output: str) -> None:
    """子ページ本文が確実に保存されていることを検証

    検証項目:
    1. state["phase_subpages"][3] が存在する
    2. 子ページ本文が空でない
    3. 子ページ本文の長さが raw_output の 30% 以上
    4. raw_output 中盤から抽出したアンカーが子ページに含まれる

    失敗時は RuntimeError を送出し、Phase 3 を失敗扱いにする。
    """
    if os.environ.get("HOKUSAI_SKIP_NOTION") == "1":
        return

    subpage_url = state.get("phase_subpages", {}).get(3)
    if not subpage_url:
        raise RuntimeError(
            "Phase 3 本文検証失敗: 子ページURLが未登録です。"
        )

    # リトライあり: Notion MCP タイムアウト対策
    import time

    from ..integrations.notion_mcp import NotionMCPClient

    max_attempts = 3
    retry_delay = 5  # 秒
    page_content = None
    last_error = None

    for attempt in range(1, max_attempts + 1):
        try:
            notion = NotionMCPClient()
            page_content = notion.get_page_content(subpage_url)
            break
        except Exception as e:
            last_error = e
            if attempt < max_attempts:
                logger.warning(
                    f"Phase 3 本文取得リトライ {attempt}/{max_attempts}: {e}"
                )
                time.sleep(retry_delay)
            else:
                raise RuntimeError(
                    f"Phase 3 本文検証失敗: 子ページ本文の取得に失敗しました"
                    f" ({max_attempts}回試行): {last_error}"
                )

    if not page_content or not page_content.strip():
        raise RuntimeError(
            "Phase 3 本文検証失敗: 子ページ本文が空です。"
        )

    raw_len = len(raw_output.strip())
    page_len = len(page_content.strip())
    if raw_len > 0 and page_len < raw_len * 0.3:
        raise RuntimeError(
            f"Phase 3 本文検証失敗: 子ページ本文が短すぎます。"
            f" raw={raw_len}文字, page={page_len}文字"
            f" (比率={page_len / raw_len:.0%}, 閾値=30%)"
        )

    anchor = _pick_body_anchor(raw_output)
    if anchor and anchor not in page_content:
        raise RuntimeError(
            f"Phase 3 本文検証失敗: 子ページに本文アンカーが見つかりません。"
            f" アンカー={anchor[:60]!r}"
        )

    logger.info(
        f"Phase 3 本文検証OK: 子ページに本文が保存されています"
        f" (raw={raw_len}, page={page_len})"
    )


def _pick_body_anchor(raw_output: str) -> str | None:
    """raw_output の中盤から非見出し行を抽出してアンカーにする。"""
    lines = raw_output.strip().splitlines()
    content_lines = [
        line.strip()
        for line in lines
        if line.strip()
        and not line.strip().startswith("#")
        and len(line.strip()) >= 10
    ]
    if not content_lines:
        return None
    mid_idx = len(content_lines) // 2
    return content_lines[mid_idx][:80]


# ---------------------------------------------------------------------------
# 直接プロンプト構築
# ---------------------------------------------------------------------------

def _build_design_check_prompt(
    task_url: str,
    research_result: str,
    cross_review_context: str = "",
) -> str:
    """Phase 3 設計チェック用の直接プロンプトを構築する

    slash skill ではなく execute_prompt() で直接実行するためのプロンプト。
    出力フォーマットをプロンプト本文に埋め込むことで、
    前置き文や要約の混入を防ぐ。
    """
    from ..prompts import get_prompt

    cross_review_section = ""
    if cross_review_context:
        cross_review_section = (
            "\n## Phase 2 クロスLLMレビュー指摘事項\n\n"
            "以下は Phase 2 事前調査に対するクロスレビューで指摘された事項です。\n"
            "設計チェック時にこれらの指摘を考慮してください。\n\n"
            f"{cross_review_context}\n"
        )

    return get_prompt(
        "phase3.design_check",
        task_url=task_url,
        research_result=research_result,
        cross_review_section=cross_review_section,
    )


def _build_design_retry_prompt(
    task_url: str,
    research_result: str,
    previous_output: str,
    validation_error: str,
    cross_review_context: str = "",
) -> str:
    """Phase 3 出力検証失敗時の再生成プロンプトを構築する。

    前回出力が仕様違反だったことを明示し、元タスク情報と調査結果を
    再注入した上で全文を規定フォーマットで再出力させる。
    """
    from ..prompts import get_prompt

    cross_review_section = ""
    if cross_review_context:
        cross_review_section = (
            f"\n## Phase 2 クロスLLMレビュー指摘事項\n\n"
            f"{cross_review_context}\n"
        )

    return get_prompt(
        "phase3.design_check_retry",
        task_url=task_url,
        research_result=research_result,
        previous_output=previous_output,
        validation_error=validation_error,
        cross_review_section=cross_review_section,
    )
