"""
Phase 4: 作業計画作成

- /dev-plan スキルを実行
- チェックリスト形式の作業計画を作成
- 変更予定ファイルを抽出してPhase 7.5で使用
- 開発計画をNotionに保存（MCP経由）
"""

import re

from ..config import get_config
from ..integrations.claude_code import ClaudeCodeClient
from ..integrations.factory import get_task_client
from ..logging_config import get_logger
from ..prompts import get_prompt, read_prompt_file
from ..state import (
    PhaseStatus,
    WorkflowState,
    add_audit_log,
    should_skip_phase,
    update_phase_status,
)
from ..utils.cross_review import execute_cross_review, format_cross_review_for_prompt
from ..utils.notion_helpers import save_to_subpage_or_create
from ..utils.output_parser import _find_prefix_heading, extract_markdown_section
from ..utils.phase_page_templates import (
    build_phase_page_content,
    initialize_phase_page_state,
)

logger = get_logger("phase4")

# 作業計画作成時に遮断する Notion 書き込み系ツール
# （hokusai が save_to_subpage_or_create() で一元管理するため、スキルの直接書き込みを防ぐ）
NOTION_WRITE_TOOLS = [
    "mcp__notion__notion-update-page",
    "mcp__notion__notion-create-pages",
    "mcp__notion__notion-create-comment",
    "mcp__notion__notion-update-data-source",
    "mcp__notion__notion-create-database",
    "mcp__notion__notion-move-pages",
    "mcp__notion__notion-duplicate-page",
]


_DEV_PLAN_START_MARKERS = ["## 開発計画", "## 実装チェックリスト", "### 計画のポイント"]


def _extract_dev_plan_content(output: str) -> str:
    """スキル出力から開発計画部分のみを抽出"""
    return extract_markdown_section(
        output,
        start_markers=_DEV_PLAN_START_MARKERS,
        end_markers=["Generated by"],
    )


def _validate_work_plan(text: str) -> tuple[bool, list[str]]:
    """work_plan の妥当性検証。(is_valid, warnings) を返す。"""
    warnings = []
    step_pattern = r'\d+\.\d+'
    steps = re.findall(step_pattern, text)
    if len(steps) < 3:
        warnings.append(f"ステップ番号が少なすぎます ({len(steps)}件)")
    has_checkboxes = '- [ ]' in text or '- [x]' in text
    has_numbered = len(steps) >= 3
    if not has_checkboxes and not has_numbered:
        warnings.append("チェックリスト形式のステップがありません")
    return (len(warnings) == 0, warnings)


def extract_expected_files_from_dev_plan(result: str) -> list[str]:
    """
    dev-planの出力から期待変更ファイルリストを抽出

    dev-planスキルは「### 変更予定ファイル」セクションに
    以下の形式でファイルパスを出力する:

    ### 変更予定ファイル
    - src/services/entity-service.ts
    - src/controllers/entity-controller.ts
    - src/pages/EntityDetail.tsx

    この関数はそのセクションを解析してファイルパスのリストを返す。
    """
    if not result:
        return []

    # 「### 変更予定ファイル」セクションを探す
    pattern = r"###\s*変更予定ファイル\s*\n((?:[-*]\s*.+\n?)+)"
    match = re.search(pattern, result)

    if not match:
        return []

    # ファイルパスを抽出
    files_section = match.group(1)
    file_pattern = r"[-*]\s*`?([^\s`]+)`?"
    files = re.findall(file_pattern, files_section)

    # ディレクトリプレフィックスに正規化
    normalized = []
    for f in files:
        # 具体的なファイルパスはそのまま
        if "." in f.split("/")[-1]:
            normalized.append(f)
        # ディレクトリパスは末尾にスラッシュを追加
        else:
            normalized.append(f.rstrip("/") + "/")

    return normalized


def phase4_plan_node(state: WorkflowState) -> WorkflowState:
    """Phase 4: 作業計画作成"""

    # スキップチェック
    if should_skip_phase(state, 4):
        logger.info("Phase 4 スキップ: 作業計画済み")
        print("⏭️  Phase 4 スキップ: 作業計画済み")
        return state

    logger.info("Phase 4 開始: 作業計画作成")
    state = update_phase_status(state, 4, PhaseStatus.IN_PROGRESS)

    try:
        config = get_config()
        claude = ClaudeCodeClient()
        logger.debug("Claude Code クライアント初期化完了")

        # /dev-plan スキルを実行
        cross_review_context = format_cross_review_for_prompt(state, source_phase=2)
        dev_plan_args = state["task_url"]
        if cross_review_context:
            dev_plan_args = f"{state['task_url']}\n\n{cross_review_context}"
            logger.info(f"/dev-plan スキルを実行: {state['task_url']} (+Phase 2 クロスレビュー指摘)")
        else:
            logger.info(f"/dev-plan スキルを実行: {state['task_url']}")

        result = claude.execute_skill(
            skill="dev-plan",
            args=dev_plan_args,
            timeout=config.skill_timeout,
            disallowed_tools=NOTION_WRITE_TOOLS,
            append_system_prompt=read_prompt_file("phase4.append_system_prompt"),
        )

        # dev-planの出力を保存（開発計画部分のみを抽出）
        raw_output = result.get("work_plan", "") or result.get("output", "")
        if isinstance(result, dict) and not raw_output:
            raw_output = str(result)
        output_text = _extract_dev_plan_content(raw_output)
        # 抽出成否判定: パーサと同じロジック（完全一致 + プレフィックスマッチ）で判定
        extraction_succeeded = (
            (output_text != raw_output)
            or _find_prefix_heading(raw_output, _DEV_PLAN_START_MARKERS) is not None
        )

        # 抽出失敗時は 1 回だけ再生成を試みる（スキルが Notion 書き込みで
        # 終了し、テキスト出力が空になるケースの救済）
        if not extraction_succeeded:
            logger.warning(
                f"Phase 4 初回出力が抽出失敗、再生成を試みます "
                f"(raw_length={len(raw_output)})"
            )
            state = add_audit_log(state, 4, "work_plan_output_retry", "warning",
                details={
                    "reason": "extraction_failed",
                    "attempt": 2,
                    "first_output_length": len(raw_output),
                    "first_output_head": raw_output[:300],
                })
            print("📋 Phase 4 出力検証失敗、再生成中...")
            retry_prompt = _build_dev_plan_retry_prompt(
                task_url=state["task_url"],
                research_result=state.get("research_result", ""),
                previous_output=raw_output,
                cross_review_context=cross_review_context,
            )
            raw_output = claude.execute_prompt(
                prompt=retry_prompt,
                timeout=config.skill_timeout,
                allow_mcp_tools=True,
                allow_file_operations=True,
                disallowed_tools=NOTION_WRITE_TOOLS,
            )
            output_text = _extract_dev_plan_content(raw_output)
            extraction_succeeded = (
                (output_text != raw_output)
                or _find_prefix_heading(raw_output, _DEV_PLAN_START_MARKERS) is not None
            )
            if extraction_succeeded:
                logger.info("Phase 4 再生成で出力検証を通過しました")

        if not extraction_succeeded:
            # 2回目も失敗: Phase 4 を失敗にする
            logger.error(f"開発計画の見出し抽出に失敗: raw output を採用しません (raw_length={len(raw_output)})")
            logger.error(f"raw output 冒頭: {repr(raw_output[:500])}")
            state = add_audit_log(state, 4, "work_plan_extraction_failed", "failed",
                details={"raw_length": len(raw_output), "raw_head": raw_output[:300]})
            state = update_phase_status(state, 4, PhaseStatus.FAILED, "work_plan_extraction_failed")
            print(f"❌ Phase 4 失敗: 開発計画の見出しが見つかりません (raw_length={len(raw_output)})")
            print(f"   raw output: {repr(raw_output[:300])}")
            return state
        state["work_plan"] = output_text
        logger.debug(f"dev-plan出力: {len(raw_output)}文字 → 抽出後: {len(output_text)}文字")

        # work_plan の妥当性検証
        is_valid, wp_warnings = _validate_work_plan(output_text)
        if wp_warnings:
            for w in wp_warnings:
                logger.warning(f"work_plan 検証: {w}")
            state = add_audit_log(state, 4, "work_plan_validation_warnings", "warning",
                details={"warnings": wp_warnings})

        # dev-planの出力から期待変更ファイルリストを抽出
        expected_files = extract_expected_files_from_dev_plan(output_text)
        state["expected_changed_files"] = expected_files
        if not expected_files:
            logger.warning("変更予定ファイルが抽出できませんでした")
            state = add_audit_log(state, 4, "missing_expected_changed_files", "warning")
        logger.info(f"変更予定ファイル抽出: {len(expected_files)}件")
        for f in expected_files:
            logger.debug(f"  - {f}")

        # Phase page metadata を初期化（表示状態はテンプレート側で導出）
        initialize_phase_page_state(state, 4)

        phase_page_content = build_phase_page_content(
            state=state,
            phase=4,
            latest_document=output_text,
            source_phase="phase4_plan",
        )

        # Notionに開発計画を子ページとして保存（cross-review より先に実行）
        state = save_to_subpage_or_create(
            state, state["task_url"], phase=4, content=phase_page_content,
            workflow_id=state.get("workflow_id", ""),
        )

        # work_plan 妥当性ゲート: Notion 保存後、検証失敗時は Phase 4 を停止
        if not is_valid:
            state = update_phase_status(state, 4, PhaseStatus.FAILED, "work_plan_validation_failed")
            state = add_audit_log(state, 4, "work_plan_validation_gate", "failed",
                details={"warnings": wp_warnings})
            print(f"❌ Phase 4 失敗: 作業計画の妥当性検証に失敗 - {wp_warnings}")
            logger.error(f"Phase 4 妥当性ゲート失敗: {wp_warnings}")
            return state

        # 親タスクページに「開発計画」が直接書き込まれている場合の警告
        if state.get("phase_subpages", {}).get(4):
            try:
                task_client = get_task_client()
                parent_content = task_client.get_section_content(state["task_url"], "開発計画")
                if parent_content:
                    logger.warning("親タスクページに「開発計画」が直接書き込まれています。"
                                  "正本は子ページです。")
                    state = add_audit_log(state, 4, "notion_dual_content_warning", "warning",
                        details={"parent_has_content": True})
            except Exception:
                pass  # 検知失敗は無視

        # Codex クロスレビュー（設定で有効時のみ）
        # 子ページ作成後に実行することで、callout が子ページに保存される
        state = execute_cross_review(state, output_text, phase=4)

        # blockモードで停止要求がある場合は、このフェーズを完了扱いにしない
        if state.get("waiting_for_human"):
            state = update_phase_status(state, 4, PhaseStatus.FAILED, "cross_review_blocked")
            state = add_audit_log(
                state, 4, "cross_review_blocked", "failed",
                details={"reason": state.get("human_input_request")},
            )
            print("🛑 Phase 4 停止: クロスLLMレビューで確認が必要です")
            return state

        state = update_phase_status(state, 4, PhaseStatus.COMPLETED)
        state = add_audit_log(state, 4, "dev_plan_completed", "success", {
            "expected_files_count": len(expected_files),
            "expected_files": expected_files,
            "work_plan_length": len(output_text),
        })

        print("✅ Phase 4 完了: 作業計画を作成しました")
        if expected_files:
            print(f"   変更予定ファイル: {len(expected_files)}件")
        logger.info("Phase 4 完了")

    except Exception as e:
        state = update_phase_status(state, 4, PhaseStatus.FAILED, str(e))
        state = add_audit_log(state, 4, "phase_failed", "error", error=str(e))
        print(f"❌ Phase 4 失敗: {e}")
        logger.error(f"Phase 4 失敗: {e}")
        raise

    return state


def _build_dev_plan_retry_prompt(
    task_url: str,
    research_result: str,
    previous_output: str,
    cross_review_context: str = "",
) -> str:
    """Phase 4 出力検証失敗時の再生成プロンプトを構築する。

    スキル実行が Notion 書き込みで終了しテキスト出力が空になった場合の救済。
    前回出力と元タスク情報を注入し、直接プロンプトで全文再出力させる。
    """
    cross_review_section = ""
    if cross_review_context:
        cross_review_section = (
            f"\n## Phase 2 クロスLLMレビュー指摘事項\n\n"
            f"{cross_review_context}\n"
        )

    return get_prompt(
        "phase4.dev_plan_retry",
        task_url=task_url,
        research_result=research_result,
        previous_output=previous_output,
        cross_review_section=cross_review_section,
    )
